// @flow

export const SINGLE_COMPATIBILITY_REQUEST = 'SINGLE_COMPATIBILITY_REQUEST';
export const SINGLE_COMPATIBILITY_SUCCESS = 'SINGLE_COMPATIBILITY_SUCCESS';
export const SINGLE_COMPATIBILITY_FAILURE = 'SINGLE_COMPATIBILITY_FAILURE';

export const GET_SKILLS_REQUEST = 'GET_SKILLS_REQUEST';
export const GET_SKILLS_SUCCESS = 'GET_SKILLS_SUCCESS';
export const GET_SKILLS_FAILURE = 'GET_SKILLS_FAILURE';

export const GET_PROGNOSIS_TODAY_REQUEST = 'GET_PROGNOSIS_TODAY_REQUEST';
export const GET_PROGNOSIS_TODAY_SUCCESS = 'GET_PROGNOSIS_TODAY_SUCCESS';
export const GET_PROGNOSIS_TODAY_FAILURE = 'GET_PROGNOSIS_TODAY_FAILURE';

export const GET_PROGNOSIS_YESTERDAY_REQUEST =
  'GET_PROGNOSIS_YESTERDAY_REQUEST';
export const GET_PROGNOSIS_YESTERDAY_SUCCESS =
  'GET_PROGNOSIS_YESTERDAY_SUCCESS';
export const GET_PROGNOSIS_YESTERDAY_FAILURE =
  'GET_PROGNOSIS_YESTERDAY_FAILURE';

export const GET_PROGNOSIS_TOMORROW_REQUEST = 'GET_PROGNOSIS_TOMORROW_REQUEST';
export const GET_PROGNOSIS_TOMORROW_SUCCESS = 'GET_PROGNOSIS_TOMORROW_SUCCESS';
export const GET_PROGNOSIS_TOMORROW_FAILURE = 'GET_PROGNOSIS_TOMORROW_FAILURE';

export const DOUBLE_COMPATIBILITY_REQUEST = 'DOUBLE_COMPATIBILITY_REQUEST';
export const DOUBLE_COMPATIBILITY_SUCCESS = 'DOUBLE_COMPATIBILITY_SUCCESS';
export const DOUBLE_COMPATIBILITY_FAILURE = 'DOUBLE_COMPATIBILITY_FAILURE';

export const GET_FEEDBACK_LINKS_REQUEST = 'GET_FEEDBACK_LINKS_REQUEST';
export const GET_FEEDBACK_LINKS_SUCCESS = 'GET_FEEDBACK_LINKS_SUCCESS';
export const GET_FEEDBACK_LINKS_FAILURE = 'GET_FEEDBACK_LINKS_FAILURE';

export const GET_FAQ_REQUEST = 'GET_FAQ_REQUEST';
export const GET_FAQ_SUCCESS = 'GET_FAQ_SUCCESS';
export const GET_FAQ_FAILURE = 'GET_FAQ_FAILURE';

export const SET_SELECTED_ANSWER = 'SET_SELECTED_ANSWER';

export const SET_AVAILABLE_PURCHASES = 'SET_AVAILABLE_PURCHASES';

export const SET_REMOTE_CONFIG = 'SET_REMOTE_CONFIG';

export const SET_USER_NAME = 'SET_USER_NAME';
