import { StyleSheet } from 'react-native';
import { ifIphoneX } from 'react-native-iphone-x-helper';
import { scale } from 'react-native-size-matters';
import { fs, hp, wp } from '../../helpers';
import { colors, fonts } from '../../variables';

const stylesF = StyleSheet.create({
  // content texts
  background: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  container: {
    paddingTop: 150,
  },
  contentContainer: {
    flex: 1,
    paddingHorizontal: wp('16.184%'),
    paddingVertical: wp('6.010%'),
  },
  content: {
    position: 'absolute',
    zIndex: 10,
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderTopRightRadius: 36,
    borderTopLeftRadius: 36,
  },
  contentTitle: {
    color: colors.darkViolet,
    fontFamily: fonts.sfProBold,
    fontSize: fs(6.039),
    // marginBottom: 15,
  },
  contentSubTitle: {
    color: colors.darkViolet,
    fontFamily: fonts.sfProMedium,
    fontSize: fs(4.106),
    marginBottom: hp('1.674%'),
  },
  contentDescription: {
    color: colors.darkViolet,
    fontFamily: fonts.sfProBold,
    fontSize: fs(3.623),
    width: wp('75%'),
  },
  contentList: {
    marginTop: hp('4.444%'),
  },
  contentListItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  contentListImage: {
    width: 50,
    height: 50,
    marginRight: 10,
  },
  contentListText: {
    color: colors.darkViolet,
    fontFamily: fonts.sfProRegular,
    fontSize: fs(3.623),
    lineHeight: fs(5),
    paddingVertical: hp('1%'),
  },
  buttonContainer: {
    marginTop: hp('4.444%'),
  },
  button: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 32,
    width: wp('85.024%'),
    paddingVertical: 10,
    // shadow
    shadowColor: colors.slateBlue,
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 1,
    shadowRadius: 15,
    elevation: 10,
  },
  buttonText: {
    color: colors.white,
    fontFamily: fonts.sfProSemibold,
    fontSize: 14,
    textAlign: 'center',
  },
  animateContainer: {
    position: 'absolute',
    width: '100%',
    justifyContent: 'center',
    flexDirection: 'column',
    alignItems: 'center',
    zIndex: 10,
  },

  // animation images
  man: {
    position: 'absolute',
    zIndex: 5,
    width: wp('15.942%'),
    height: wp('50%'),
    left: '35%',
    top: hp('28.973%'),
  },
  circle: {
    position: 'relative',
    zIndex: 4,
    width: wp('85%'),
    height: wp('85%'),
  },
  seven: {
    position: 'absolute',
    left: '20%',
    top: '21%',
    width: wp('10%'),
    height: wp('10%'),
  },
  energy: {
    position: 'absolute',
    top: '28%',
    right: '15%',
    width: wp('10%'),
    height: wp('10%'),
  },
  five: {
    position: 'absolute',
    bottom: '29%',
    right: '15%',
    width: wp('17%'),
    height: wp('17%'),
    zIndex: 4,
  },
  head: {
    position: 'absolute',
    bottom: hp('10%'),
    left: '10%',
    zIndex: 4,
    width: wp('14%'),
    height: wp('14%'),
  },
});

const stylesS = StyleSheet.create({
  // content texts
  background: {
    flex: 1,
  },
  container: {
    ...ifIphoneX({ paddingTop: 50 }, { paddingTop: 15 }),
  },
  contentContainer: {
    flex: 1,
    ...ifIphoneX({ paddingTop: 100 }, { paddingTop: 0 }),
    alignItems: 'center',
  },
  content: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
  },
  contentTitle: {
    color: colors.white,
    fontFamily: fonts.sfProSemibold,
    fontSize: scale(28),
    textAlign: 'center',
    marginTop: scale(10),
  },
  contentList: {
    flex: 1,
    marginTop: 7,
  },
  contentListItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  contentListImage: {
    width: 22,
    height: 22,
    marginRight: 10,
  },
  contentListText: {
    color: colors.white,
    fontFamily: fonts.sfProRegular,
    fontSize: 18,
    lineHeight: fs(5),
  },
  button1: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    width: wp('85.024%'),
    paddingVertical: 15,
    // shadow
    shadowColor: '#ffca00',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 1,
    shadowRadius: 15,
    elevation: 10,
  },
  topCard: {
    width: wp('93%'),
    minHeight: scale(140),
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: scale(20),
    marginBottom: scale(20),
    padding: 20,
    borderRadius: 16,
  },
  topCardDescription: {
    color: colors.white,
    fontSize: 18,
    fontFamily: fonts.sfProMedium,
    lineHeight: 24,
    textAlign: 'center',
  },
  topCardAuthor: {
    marginTop: scale(10),
    color: colors.lightGray,
    fontSize: 14,
    fontFamily: fonts.sfProRegular,
    alignSelf: 'flex-end',
  },
  cardsContainer: {
    flex: 1,
    width: wp('93%'),
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  card: {
    height: 135,
    width: wp('43%'),
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 10,
    paddingHorizontal: 20,
    padding: 20,
  },
  activeSubscription: {
    borderColor: '#ffca00',
    borderWidth: 1,
  },
  cardLabel: {
    position: 'absolute',
    width: 104,
    height: 24,
    justifyContent: 'center',
    backgroundColor: colors.shadowYellow,
    borderRadius: 16,
  },
  cardLabelContainer: {
    bottom: 0,
    top: 0,
    left: 0,
    right: 0,
    zIndex: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardLabelText: {
    color: colors.white,
    fontFamily: fonts.sfProMedium,
    fontSize: 14,
    textAlign: 'center',
  },
  smallFontText: {
    color: colors.white,
    fontSize: 14,
    fontFamily: fonts.sfProRegular,
  },
  topTextContainer: {
    height: 20,
    justifyContent: 'center',
  },
  touchableYellowButton: {
    marginTop: 60,
  },
  restoreContainer: {
    paddingRight: 20,
    paddingVertical: 5,
  },
  restore: {
    fontSize: 18,
    color: colors.white,
    fontFamily: fonts.sfProRegular,
  },
  buttonText: {
    color: colors.white,
    fontFamily: fonts.sfProSemibold,
    fontSize: 16,
    textAlign: 'center',
  },
  cardTopText: {
    color: colors.white,
    fontFamily: fonts.sfProBold,
    fontSize: 18,
    textAlign: 'center',
  },
  buttonSubText: {
    color: colors.onBoardingDesc,
    fontFamily: fonts.sfProRegular,
    fontSize: fs(2.899),
    textAlign: 'center',
  },
  descContainer: {
    marginVertical: 15,
    width: wp('85%'),
  },
  descText: {
    color: colors.onBoardingDesc,
    fontFamily: fonts.montserratExtraLight,
    fontSize: fs(2.8),
    lineHeight: fs(4),
  },
  privacyLinkContainer: {
    width: '50%',
    flex: 1,
  },
  animateContainer: {
    width: '100%',
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 5,
  },
  // animation images
  privacyLinks: {
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 30,
    paddingBottom: 30,
  },
  privacyLink: {
    color: colors.white,
    fontFamily: fonts.sfProMedium,
    fontSize: 14,
    lineHeight: fs(4.348),
    marginHorizontal: 15,
  },
  close: {
    alignSelf: 'flex-start',
    marginLeft: 10,
  },
  closeIcon: {
    width: 18,
    height: 18,
    margin: 10,
  },
  restoreButton: {
    color: '#7c7c7c',
    fontFamily: fonts.montserratLight,
    fontSize: fs(4.3),
    lineHeight: fs(4.3),
  },
  safeAreaContainer: {
    flex: 1,
    backgroundColor: '#433693',
  },
  stars: {
    height: 22,
    width: 160,
    marginBottom: 20,
  },
  continueButtonContainer: {
    width: wp('85%'),
    padding: 12,
    borderRadius: 16,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  spinnerButtonContainer: {
    width: wp('75%'),
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 16,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  continueArrow: {
    width: 18,
    height: 12,
    marginLeft: 10,
  },
  continueContainer: {
    paddingTop: 20,
    paddingBottom: 10,
    shadowColor: '#ffca00',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 1,
    shadowRadius: 15,
  },
});

const Styles2 = StyleSheet.create({
  background: {
    flex: 1,
  },
  container: {
    ...ifIphoneX({ paddingTop: 50, flex: 1 }, { paddingTop: 20, flex: 1 }),
  },
  contentContainer: {
    flex: 1,
    ...ifIphoneX({ paddingTop: 10 }, { paddingTop: 0 }),
    alignItems: 'center',
  },
  content: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
  },
  contentTitle: {
    color: colors.white,
    fontFamily: fonts.sfProSemibold,
    fontSize: scale(28),
    textAlign: 'center',
    marginTop: scale(30),
  },
  contentList: {
    flex: 1,
    marginTop: 7,
  },
  contentListItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  contentListImage: {
    width: 22,
    height: 22,
    marginRight: 10,
  },
  contentListText: {
    color: colors.white,
    fontFamily: fonts.sfProRegular,
    fontSize: 18,
    lineHeight: fs(5),
  },
  button1: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    width: wp('85.024%'),
    paddingVertical: 15,
    // shadow
    shadowColor: '#ffca00',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 1,
    shadowRadius: 15,
    elevation: 10,
  },
  topCard: {
    width: wp('93%'),
    minHeight: scale(140),
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: scale(20),
    padding: 20,
    borderRadius: 16,
  },
  topCardDescription: {
    color: colors.white,
    fontSize: 18,
    fontFamily: fonts.sfProMedium,
    lineHeight: 24,
    textAlign: 'center',
  },
  topCardAuthor: {
    marginTop: scale(10),
    color: colors.lightGray,
    fontSize: 14,
    fontFamily: fonts.sfProRegular,
    alignSelf: 'flex-end',
  },
  cardsContainer: {
    flex: 1,
    width: wp('93%'),
    flexDirection: 'row',
    justifyContent: 'space-between',
    ...ifIphoneX({ paddingTop: 80 }, {}),
  },
  card: {
    ...ifIphoneX({ height: 180 }, { height: 135 }),
    width: wp('43%'),
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 10,
    paddingHorizontal: 20,
    padding: 20,
  },
  activeSubscription: {
    borderColor: '#ffca00',
    borderWidth: 1,
  },
  cardLabel: {
    position: 'absolute',
    width: 104,
    height: 24,
    justifyContent: 'center',
    backgroundColor: colors.shadowYellow,
    borderRadius: 16,
  },
  cardLabelContainer: {
    bottom: 0,
    top: 0,
    left: 0,
    right: 0,
    zIndex: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardLabelText: {
    color: colors.white,
    fontFamily: fonts.sfProMedium,
    fontSize: 14,
    textAlign: 'center',
  },
  smallFontText: {
    color: colors.white,
    fontSize: 14,
    fontFamily: fonts.sfProRegular,
  },
  topTextContainer: {
    height: 20,
    justifyContent: 'center',
  },
  touchableYellowButton: {
    marginTop: 60,
  },
  restoreContainer: {
    paddingRight: 20,
    paddingVertical: 5,
  },
  restore: {
    fontSize: 18,
    color: colors.white,
    fontFamily: fonts.sfProRegular,
  },
  buttonText: {
    color: colors.white,
    fontFamily: fonts.sfProSemibold,
    fontSize: 16,
    textAlign: 'center',
  },
  cardTopText: {
    color: colors.shadowYellow,
    fontFamily: fonts.sfProBold,
    fontSize: 18,
    textAlign: 'center',
  },
  buttonSubText: {
    color: colors.white,
    fontFamily: fonts.sfProRegular,
    fontSize: fs(3.8),
    textAlign: 'center',
  },
  descContainer: {
    marginVertical: 15,
    width: wp('85%'),
  },
  descText: {
    color: colors.onBoardingDesc,
    fontFamily: fonts.montserratExtraLight,
    fontSize: fs(2.8),
    lineHeight: fs(4),
  },
  privacyLinkContainer: {
    width: '50%',
    flex: 1,
  },
  animateContainer: {
    width: '100%',
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 5,
  },
  // animation images
  privacyLinks: {
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    ...ifIphoneX({ paddingBottom: 35 }, { paddingBottom: 20 }),
    paddingTop: 5,
  },
  privacyLink: {
    color: colors.lightGray,
    fontFamily: fonts.sfProMedium,
    fontSize: 14,
    lineHeight: fs(4.348),
    marginHorizontal: 15,
    textDecorationLine: 'underline',
  },
  close: {
    alignSelf: 'flex-start',
    marginLeft: 10,
  },
  closeIcon: {
    width: 18,
    height: 18,
    margin: 10,
  },
  restoreButton: {
    color: '#7c7c7c',
    fontFamily: fonts.montserratLight,
    fontSize: fs(4.3),
    lineHeight: fs(4.3),
  },
  safeAreaContainer: {
    flex: 1,
    backgroundColor: '#433693',
  },
  stars: {
    height: 22,
    width: 160,
    marginBottom: 20,
  },
  continueButtonContainer: {
    width: wp('85%'),
    padding: 12,
    borderRadius: 16,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  spinnerButtonContainer: {
    width: wp('75%'),
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 16,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  continueArrow: {
    width: 18,
    height: 12,
    marginLeft: 10,
  },
  continueContainer: {
    paddingTop: 30,
    paddingBottom: 10,
    shadowColor: '#ffca00',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 1,
    shadowRadius: 15,
  },
});

const Styles3 = StyleSheet.create({
  background: {
    flex: 1,
  },
  container: {
    ...ifIphoneX({ paddingTop: 50, flex: 1 }, { paddingTop: 20, flex: 1 }),
  },
  contentContainer: {
    flex: 1,
    ...ifIphoneX({ paddingTop: 20 }, { paddingTop: 0 }),
    alignItems: 'center',
  },
  content: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
  },
  contentTitle: {
    color: colors.white,
    fontFamily: fonts.sfProSemibold,
    fontSize: scale(22),
    textAlign: 'center',
    marginTop: scale(10),
  },
  contentList: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'flex-start',
    paddingBottom: 15,
    ...ifIphoneX({ marginTop: 60 }, { marginTop: 7 }),
  },
  contentListItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 5,
  },
  contentListImage: {
    width: 24,
    height: 24,
    marginRight: 10,
  },
  contentListText: {
    color: colors.white,
    fontFamily: fonts.sfProRegular,
    fontSize: 20,
    lineHeight: fs(5),
  },
  button1: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    width: wp('85.024%'),
    paddingVertical: 15,
    // shadow
    shadowColor: '#ffca00',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 1,
    shadowRadius: 15,
    elevation: 10,
  },
  topCard: {
    width: wp('93%'),
    minHeight: scale(140),
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: scale(20),
    marginBottom: scale(20),
    padding: 20,
    borderRadius: 16,
  },
  topCardDescription: {
    color: colors.white,
    fontSize: 18,
    fontFamily: fonts.sfProMedium,
    lineHeight: 24,
    textAlign: 'center',
  },
  topCardAuthor: {
    marginTop: scale(10),
    color: colors.lightGray,
    fontSize: 14,
    fontFamily: fonts.sfProRegular,
    alignSelf: 'flex-end',
  },
  cardsContainer: {
    flex: 1,
    width: wp('93%'),
    flexDirection: 'column',
    ...ifIphoneX(
      { justifyContent: 'center' },
      { justifyContent: 'space-between' },
    ),
    alignItems: 'center',
  },
  card: {
    ...ifIphoneX({ height: wp('14%') }, { height: wp('12%') }),
    width: wp('80%'),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 16,
    padding: 20,
    margin: 10,
  },
  activeSubscription: {
    borderColor: '#ffca00',
    borderWidth: 1,
  },
  cardLabel: {
    position: 'absolute',
    width: 104,
    height: 24,
    justifyContent: 'center',
    backgroundColor: colors.shadowYellow,
    borderRadius: 16,
  },
  cardLabelContainer: {
    bottom: 0,
    top: 6,
    left: 0,
    right: 0,
    zIndex: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardLabelText: {
    color: colors.white,
    fontFamily: fonts.sfProMedium,
    fontSize: 16,
    textAlign: 'center',
  },
  textContainer: {
    flex: 1,
    width: wp('93%'),
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  textLink: {
    color: colors.white,
    fontFamily: fonts.sfProMedium,
    fontSize: 14,
    textAlign: 'center',
    textDecorationLine: 'underline',
    ...ifIphoneX(
      { paddingTop: 70, paddingBottom: 0 },
      { paddingTop: 23, paddingBottom: 0 },
    ),
  },
  smallFontText: {
    color: colors.white,
    fontSize: 14,
    fontFamily: fonts.sfProRegular,
  },
  topTextContainer: {
    height: wp('5%'),
    justifyContent: 'center',
  },
  restoreContainer: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'flex-end',
    paddingRight: 20,
    paddingVertical: 5,
  },
  restore: {
    fontSize: 18,
    color: colors.white,
    fontFamily: fonts.sfProRegular,
  },
  buttonText: {
    color: colors.white,
    fontFamily: fonts.sfProSemibold,
    fontSize: 16,
    textAlign: 'center',
  },
  cardTopText: {
    color: colors.white,
    fontFamily: fonts.sfProBold,
    fontSize: 18,
    textAlign: 'center',
  },
  buttonSubText: {
    color: colors.onBoardingDesc,
    fontFamily: fonts.sfProRegular,
    fontSize: fs(2.899),
    textAlign: 'center',
  },
  descContainer: {
    marginVertical: 15,
    width: wp('85%'),
  },
  descText: {
    color: colors.onBoardingDesc,
    fontFamily: fonts.montserratExtraLight,
    fontSize: fs(2.8),
    lineHeight: fs(4),
  },
  privacyLinkContainer: {
    width: '50%',
    flex: 1,
  },
  animateContainer: {
    width: '100%',
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
  },
  // animation images
  privacyLinks: {
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    ...ifIphoneX({ paddingBottom: 35 }, { paddingBottom: 20 }),
    paddingTop: 5,
  },
  privacyLink: {
    color: colors.lightGray,
    fontFamily: fonts.sfProMedium,
    fontSize: 14,
    lineHeight: fs(4.348),
    marginHorizontal: 15,
    textDecorationLine: 'underline',
  },
  close: {
    flex: 1,
    flexDirection: 'column',
    alignSelf: 'flex-start',
    marginLeft: 10,
  },
  closeIcon: {
    width: 18,
    height: 18,
    margin: 10,
  },
  restoreButton: {
    color: '#7c7c7c',
    fontFamily: fonts.montserratLight,
    fontSize: fs(4.3),
    lineHeight: fs(4.3),
  },
  safeAreaContainer: {
    flex: 1,
    backgroundColor: '#433693',
  },
  stars: {
    height: 22,
    width: 160,
    marginBottom: 20,
  },
  continueButtonContainer: {
    width: wp('85%'),
    padding: 12,
    borderRadius: 16,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  spinnerButtonContainer: {
    width: wp('75%'),
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 16,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  continueArrow: {
    width: 18,
    height: 12,
    marginLeft: 10,
  },
  continueContainer: {
    paddingTop: 30,
    paddingBottom: 10,
    shadowColor: '#ffca00',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 1,
    shadowRadius: 15,
  },
});

export { stylesF, stylesS, Styles2, Styles3 };
