export const Events = {
  TabBar: {
    PersonalityClick: 'TabBar_Personality_click',
    DailyNumerologyClick: 'TabBar_DailyNumerology_click',
    CompatibilityClick: 'TabBar_Compatibility_click',
  },
  Onboarding: {
    StartButtonClick: 'Onboarding_StartButton_click',
    NameInputClick: 'Onboarding_NameInput_click',
    NameNextButtonClick: 'Onboarding_NameNextButton_click',
    BirthdayNextButtonClick: 'Onboarding_BirthdayNextButton_click',
    ProblemCheckboxClick: 'Onboarding_ProblemCheckBox_click',
    ProblemNextButtonClick: 'Onboarding_ProblemNextButton_click',
    QualitiesCheckboxClick: 'Onboarding_QualitiesCheckBox_click',
    QualitiesNextButtonClick: 'Onboarding_QualitiesNextButton_click',
    StrengthsCheckboxClick: 'Onboarding_StrengthsCheckBox_click',
    StrengthsNextButtonClick: 'Onboarding_StrengthsNextButton_click',
    PersonalizationScreenShowed: 'Onboarding_PersonalizationScreen_showed',
  },
  Paywall: {
    RestoreButtonClick: 'Paywall_RestoreButton_click',
    ExitIconClick: 'Paywall_ExitIcon_click',
    YearButtonClick: 'Paywall_YearButton_click',
    MonthButtonClick: 'Paywall_MonthButton_click',
    ContinueButtonClick: 'Paywall_ContinueButton_click',
    WinWinShowed: 'Paywall_WinWin_showed',
    ErrorShowed: 'Paywall_Error_showed',
  },
  Personality: {
    SkillsButtonClick: 'Personality_SkillsButton_click',
    PsychomatrixButtonClick: 'Personality_PsychomatrixButton_click',
    StrengthUnlockButtonClick: 'Personality_StrengthUnlockButton_click',
    WeaknessUnlockButtonClick: 'Personality_WeaknessUnlockButton_click',
    ImportantUnlockButtonClick: 'Personality_ImportantUnlockButton_click',
    AskUsButtonClick: 'Personality_AskUsButton_click',
    DataButtonClick: 'Personality_DataButton_click',
    TryItNowButtonClick: 'Personality_TryItNowButton_click',
    HealthUnlockButtonClick: 'Personality_HealthUnlockButton_click',
    LuckUnlockButtonClick: 'Personality_LuckUnlockButton_click',
    VitalUnlockButtonClick: 'Personality_VitalUnlockButton_click',
    LogicUnlockButtonClick: 'Personality_LogicUnlockButton_click',
    DutyUnlockButtonClick: 'Personality_DutyUnlockButton_click',
    CognitiveUnlockButtonClick: 'Personality_CognitiveUnlockButton_click',
    LaborUnlockButtonClick: 'Personality_LaborUnlockButton_click',
    IntellectUnlockButtonClick: 'Personality_IntellectUnlockButton_click',
  },
  DailyNumerology: {
    YesterdayButtonClick: 'DailyNumerology_YesterdayButton_click',
    TodayButtonClick: 'DailyNumerology_TodayButton_click',
    TomorrowButtonClick: 'DailyNumerology_TomorrowButton_click',
    JobUnlockButtonClick: 'DailyNumerology_JobUnlockButton_click',
    ProsperityUnlockButtonClick: 'DailyNumerology_ProsperityUnlockButton_click',
    LoveUnlockButtonClick: 'DailyNumerology_LoveUnlockButton_click',
    HealthUnlockButtonClick: 'DailyNumerology_HealthUnlockButton_click',
    SelfUnlockButtonClick: 'DailyNumerology_SelfUnlockButton_click',
    AskUsButtonClick: 'DailyNumerology_AskUsButton_click',
  },
  Compatibility: {
    WomanClick: 'Compatibility_Woman_click',
    ManClick: 'Compatibility_Man_click',
    LoveUnlockButtonClick: 'Compatibility_LoveUnlockButton_click',
  },
  TryFree: {
    ButtonClick: 'TryFree_Button_click',
  },
};
